GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Derek Nash",
    "dateOfBirth": "6/6/2052",
    "ssn": "#969c1f-specific",
    "gender": "female",
    "occupation": "software engineer"
}