# Get all contacts in db
GET http://localhost:3000/api/persons

###
# Create a contact
POST http://localhost:3000/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "number": "123"
}

###
# Update a contact with specific id
PUT http://localhost:3000/api/persons HTTP/1.1
Content-Type: application/json

{
    "id": "666640eb334f6eb12b7b5dbd",
    "number": "123"
    
}

###
# Get Contact Details
GET http://localhost:3000/api/persons/1

###
# Delete a contact with specific id
DELETE  http://localhost:3000/api/persons/6666105a12110b98e19a9f48

###
# Contacts info
GET http://localhost:3000/api/persons/info