#! Get all blogs
GET http://localhost:3000/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IldhbHRlciIsImlkIjoiNjY2OWY1OWEyODA3MTg4YzczZGIzM2QyIiwiaWF0IjoxNzE4MjIyNDUyLCJleHAiOjE3MTgyMjMzNTJ9.OHj66taosP4DXa2BFDlYiTHvKyZfx3HL6kFG1k0rIpc

###
#! Create a new blog
POST http://localhost:3000/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "press coming",
    "url": "http://hewa.tn/ozfajin",
    "userId": "666999f17e653c2edd123e28"
}
###

#! get a blog detail by id
GET http://localhost:3000/api/blogs/6669e4bfc580801f6434efad

###

#! Delete a blog detail by id
DELETE http://localhost:3000/api/blogs/6669e6aa2d15bee1747ba586

###
#! Update a blog by id
PUT http://localhost:3000/api/blogs/66672bded53ed60e496deb89 HTTP/1.1
Content-Type: application/json

{
    "title": "scientific winter",
    "user": "",
    "url": "http://vobabodog.jm/jiru"
}